name: PHP Composer download and dependency run

on:
    workflow_call:
        inputs:
            config-pah:
                required: true
                type: string
        secrets:
            envPAT:
                required: true
jobs:
    
    


